# 2 УРОК ГРУППИРОВКА И АГРЕГАТНЫЕ ФУНКЦИИ

## ШАГ 4

### Продолжим работать с таблицей checks!

Посчитайте, сколько покупок приходится на каждого клиента, указав имя столбца как NumChecks. Результирующую таблицу с UserID, NumChecks отсортируйте по убыванию (DESC) нового столбца. Ограничение вывода – 10.

Подсказки

##### ОТВЕТ:

In [ ]:
SELECT UserID,
        count(*) AS NumChecks
        
FROM checks

GROUP BY UserID

ORDER BY NumChecks DESC

LIMIT 10

## ШАГ 5

Давайте немного усложним задачу, и посчитаем ещё и сумму сделанных покупок в рублях (Rub).

Выведите в результирующую таблицу UserID клиентов, количество сделанных покупок (NumChecks) и сумму потраченных денег (Revenue). Результат отсортируйте по убыванию Revenue, оставив 10 записей.

##### ОТВЕТ:

In [ ]:
SELECT UserID,
        count(*) AS NumChecks,
        SUM(Rub) AS Revenue
        
FROM checks

GROUP BY UserID

ORDER BY Revenue DESC

LIMIT 10

## ШАГ 6

Теперь давайте попробуем с помощью группировки и агрегатных функций посмотреть динамику трат клиентов. Для этого нужно посчитать по дням минимальный, средний, и максимальный чек. Иными словами, необходимо сгруппироваться по датам, и использовать агрегатные функции MIN, AVG, MAX.

Выведите минимальный (MinCheck), максимальный (MaxCheck) и средний (AvgCheck) чек по дням. В результирующей таблице используйте сортировку по убыванию (DESC) столбца BuyDate. Как и на предыдущем шаге, ограничение на вывод равно 10.

##### ОТВЕТ:

In [ ]:
SELECT BuyDate,
        MIN(Rub) AS MinCheck,
        MAX(Rub) AS MaxCheck,
        AVG(Rub) AS AvgCheck
FROM checks

GROUP BY BuyDate

ORDER BY BuyDate DESC

LIMIT 10

## ШАГ 7

Представим, что для проведения новой акции нам потребовалось выгрузить сегмент пользователей, которые приносят наибольшую выручку.

Найдите покупателей, сумма покупок которых превышает 10 000 рублей (Rub). Для этого сгруппируйте пользователей по UserID, затем примените нужную агрегатную функцию и назовите новую колонку Revenue. Отфильтруйте нужные значения, результат отсортируйте по убыванию UserID и выведите 10 строк.

Note: В данном задании под капотом используется другая проверяющая система, поэтому запрос чувствителен к регистру.

##### ОТВЕТ:

In [ ]:
SELECT UserID,
        SUM(Rub) AS Revenue
      
FROM checks

GROUP BY UserID

HAVING Revenue > 10000

ORDER BY UserID DESC

LIMIT 10

## ШАГ 8

В этой и последующих задачах мы будем работать с таблицей retail в ClickHouse, которая содержит данные о покупках. 

Задания выполняются в ClickHouse, в качестве ответа, как правило, нужно будет вписывать значения какого-либо поля из результирующей таблицы.

Как подключиться к Clickhouse

Таблица включает следующие поля: 

InvoiceNo — идентификатор покупки
StockCode — идентификатор товара на складе
Description — текстовое описание товара
Quantity — количество товара
InvoiceDate — дата покупки
UnitPrice — цена товара
CustomerID — идентификатор покупателя
Country — страна
Представим, что к вам пришел менеджер с проблемой: за последний месяц он наблюдает снижение выручки в некоторых регионах и хочет определить возможную причину этого снижения. Для начала можно сгруппировать данные о выручке по странам и найти среди них топ-5 стран по величине выручки, так как интереснее всего нам будет смотреть именно на данные этих стран.

Посчитайте выручку (Revenue) по странам и отсортируйте таблицу в порядке убывания выручки. В качестве ответа скопируйте название страны с самой высокой выручкой.  Обратите внимание, что в изначальной таблице указана цена одной единицы товара (UnitPrice) и количество купленного товара (Quantity), а не выручка, и для получения Revenue нужно будет использовать агрегирующую функцию Sum и оператор умножения *.

##### ОТВЕТ: United Kingdom

## ШАГ 9

В качестве более подробного описания выручки по странам можно посмотреть, каково среднее количество купленных товаров и средняя цена товара в покупках, совершенных в определенной стране.

Посчитайте среднее число купленных товаров по стране и среднюю цену товара, сгруппировав данные по странам и используя агрегирующую функцию Avg, и отсортируйте по убыванию средней цены товара (DESC).

Обратите внимание, что в данных встречаются строки с Description 'Manual', которые включают данные об удаленных из чека позициях. Для получения правильного ответа такие строки необходимо отфильтровать с использованием операторов WHERE и неравенства !=.

В качестве ответа впишите название страны, в которой самая высокая средняя цена за купленный товар.

##### ОТВЕТ : Canada

## ШАГ 10

Теперь посмотрим на динамику общей суммы выручки по месяцам.

Посчитайте выручку (Revenue) по месяцам (обратите внимание, что в таблице указана цена одной единицы товара и количество купленного товара), округлив InvoiceDate к началу месяца с помощью toStartOfMonth().

В качестве ответа укажите сумму выручки (Revenue) из первой строки результирующей таблицы, используя сортировку по убыванию (DESC) по столбцу Revenue. Не забывайте отфильтровать строки по условию Description != 'Manual'

##### ОТВЕТ: 1130664.25

# 11

Давайте посмотрим на динамику выручки от покупателей, которые в среднем покупают самые дорогие товары.  

В качестве целевой метрики будем использовать среднюю цену купленного товара (UnitPrice), данные посмотрим за март 2011 года.

Посчитайте среднюю цену товара клиента (UnitPrice) с группировкой по id покупателя, используя агрегирующую функцию Avg, 

затем выведите строки с покупками тех покупателей, у которых самая высокая средняя цена купленного товара в марте. 

Не забывайте отфильтровать строки по условию Description != 'Manual'. 

В качестве ответа впишите CustomerID покупателя с самой высокой средней ценой купленного товара.

In [ ]:
Здесь нужно применить агрегатную функцию `AVG` к колонке `UnitPrice`, группировку выполнить по id покупателя, отфильтровать значение 'Manual' в поле `Description` и отобрать записи только за март 2011 года 

(для этого нужно применить функцию `toStartOfMonth()` к колонке `InvoiceDate`).

In [ ]:
SELECT CustomerID,
        AVG(UnitPrice) AS AVG_price
    
FROM default.retail
WHERE Description != 'Manual' AND
    toStartOfMonth(InvoiceDate) = toDate('2011-03-01')
GROUP BY CustomerID
ORDER BY AVG_price DESC
LIMIT 10

In [ ]:
13452	295
13983	145
16692	78.725
15257	37.7125
12980	34.95
12881	32.971428571428575
16061	29.95
17817	18.653846153846153
14114	16.45
13316	16.2725

###### ОТВЕТ: 13452

## 12

Давайте попробуем ответить на следующий вопрос:

"Как изменилось среднее, минимальное и максимальное количество купленного товара в стране с наибольшей выручкойв течение последних месяцев?"

Для этого нужно сгруппировать данные по странам и месяцам, посчитать среднее (Avg), минимальное (Min) и максимальное (Max) количество купленных товаров (Quantity), и отсортировать данные по месяцу, применить фильтр по стране (нам нужны данные из страны с наибольшей выручкой из задания 8 (step 8)). Если обратить внимание на полученное значение минимального количества товаров, то станет понятно, что там есть отрицательные значения, которые следует отфильтровать (также не забывайте отфильтровывать значения с Description != 'Manual').

В качестве ответа скопируйте наибольшее историческое значение среднего числа купленных товаров для этой страны.

In [ ]:
Здесь нам понадобится ответ из задачи 7 (номер шага - 8). 

Нужно применить агрегирующие функции `Min`, `Max` и `Avg` к колонке `Quantity`, группировку использовать по месяцу. В качестве фильтров нужно отобрать значение **страны** из задачи 7, убрать `Description` 'Manual' и оставить только положительные значения `Quantity`. 

Проверьте, что применяете фильтр **до аггрегации**

In [ ]:
SELECT 
        toStartOfMonth(InvoiceDate) AS mohth_,
        AVG(Quantity) AS AVG_Quantity,
        MIN(Quantity) AS MIN_Quantity,
        MAX(Quantity) AS MAX_Quantity
FROM default.retail
WHERE Description != 'Manual' AND
    Country = ('United Kingdom') AND
    Quantity > 0
GROUP BY mohth_
ORDER BY mohth_ DESC
LIMIT 10

In [ ]:
2011-12-01	16.44956626353448	1	80995
2011-11-01	9.86735405713508	1	12540
2011-10-01	10.887973452340084	1	4800
2011-09-01	12.748890885606784	1	1944
2011-08-01	13.458127652204036	1	2880
2011-07-01	12.872762744931716	1	3186
2011-06-01	11.853255136914054	1	1600
2011-05-01	11.97955862506946	1	4300
2011-04-01	12.48990165507316	1	3114
2011-03-01	11.51296049341557	1	2160
2011-02-01	12.018706333107955	1	3906
2011-01-01	15.33366396649584	1	74215

###### ОТВЕТ: 16.44956626353448